# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0004_auto_20170921_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='book_authors.books'),
        ),
    ]
