# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0005_auto_20170921_0503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
    ]
