# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20170920_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninjas',
            name='dojos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojo_ninjas.Dojos'),
        ),
    ]
